proxmox:
    user: ENC[AES256_GCM,data:f1nk3FsE5ig=,iv:YkqPoz/PEaC3zXLrNhs9BGPxqnAj/A/QmF5YiLwx4oA=,tag:J5bxgceGgX9+l+yY8FtHBA==,type:str]
    password: ENC[AES256_GCM,data:EskHvYOLmruhVXE=,iv:Tkg9DDUTRpQ68nt+6HP6qf5p2VyoDvnILp5zNmbgGDk=,tag:jKWkwzCRCdSE2l1vnf3OxA==,type:str]
github:
    deploy-key: ENC[AES256_GCM,data:ZdejZLQCApiumKFfUhHp5NmaoqmWXIc6FheirH71WOaq/HRyc/mR/FReTPkD9Iawhxdqb2lMG8TMZBBIjK6IZY+zEU4Rfk0qAapHq2Zl8N9eIJQJn+ilIo0G7ITgH7YJqOkUSZ4m2EuOgIWkag0SD3TFRzfllyiKROV69dIfeJMj2obCjFp3L3SJLHi1WD5BE/1Cq83ZBt/3F84ZfR1EpyKrwRJeP9lVKY04yjE0QXoO/mbQOaRDbAn7ArNctc5DXxafVXWSAGaSdm4U522oX7J4Qkg5eev6C+7biN9b4gpMGE2OaFCcBH51yJ41ODXY/I+s60um7MSvpmoq2U8JE+0tvtoAeJ/CMo0J6u0iuYsGtMMpxjEHk/m25m7kZ8QSdQeVfVxEDJ66BGGwftqlfeKZPGQZEtfihIO1W5RC+ZJXkGiaCcpgU9xehYAv3e8kenz33MB154k6G/dRJ9L4Lh3iIi0kUXWl0xJNex50JAHltoau24VMRYgMIbzenxYKfsaQOF+XulcNwL/tGWl1CA0oP5gkPQxx4G0kyVporK9xCRpWv2a8sbJI725rnGr98nVwosGodngseCnM4LpGPjsi7crZ2hOFHjHSamaM8FBxffYbp2Z04+7mJW3kRISKV5AOH+3ilBJ+p7yby9R5pd/ju0WxKbk6RuRgqHZfAiTS0z+WwsTmkPOTPeWM41HLfZnuuLvOjHuzT8QvcXkh+HTjIYKdNpMTsXVp2FYOvUhDXbJFnaejwx/1eUqopTB/bOMDTYoOcKosQb6uHI3r36qOJJqvbVL2GbQSl+z5ICKC84al8IGY3i2dIksPipzH4btEOnnQJVLYtctk4RPNyVPmxvC8a1qooApaxpZ+bcLeR7bb8yvA4hjk1iWLN+g63DlIpjw5eSOyywkmoe/OHM5xj0OnxGFaTPuSHrOJCng7CgNYO7KTnSG6TIMvp5I2wC+D/9GsSK4vdobMcYlA,iv:EnQArZ+ppc1HHtV631Xd+mPDTLT/yXSfFTev10q6tQs=,tag:6gTbNNdbU+31aiEz1LykrQ==,type:str]
age:
    agekey: ENC[AES256_GCM,data:q37100gpm6ygzzxeVtEunWnWDDmDiai2KQRyflFlgenHgzhkz3jYdV0jKYuAA8C4wbGQsFFF32LUPIKDm7xKM0i2ZaC2Fj+YmKg=,iv:ximfoeiNDln0rkpTpv7l6l5C0JtLCRBKAO1kU+4vBxg=,tag:8S1LxuEntYlC8bw9oxfvBw==,type:str]
    public: ENC[AES256_GCM,data:zF1UXO8TzQ48ls1MCWdg31HSDW4cUcTNLLVEOWWsgocuQiDexGUSpDNmhXIr4D94Olz2kLqyQG3H2ry3/X8=,iv:TfvfUtluD30rnFfl13vtIqFdkjckJU8kEbFJNgO23qw=,tag:filZhTSWGaHvQBjSA4KTXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lxv87gr62gf94et9cgj85ae7xuuxr3lqf0j959vewh4f3pdp050sqakepu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUWNwODRzcDU5TUlpYlVE
            U3NYZEw4QmVMTzBWSzNUUFRONE1kRDlxd0RnCi9QVkdLV2VWSTNBdXFlbEE4NFlK
            a254OVd4aUJCandYMWRPTlFodm1QM28KLS0tIFBnc0RqcTFJVldWc0EzZmVxdCtk
            N29hMi96NDdWa1htY0NQc1BrUkppeTgKOTKeXffTYYFe/7twE92pd+dKLkSOIk0w
            70AguSXETGjOrZMZz813pxle91oSYd0YoHQNGt3Yzr9rMovVR89/FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T11:25:38Z"
    mac: ENC[AES256_GCM,data:LYuKECZ7yMwkeMPXAi92/la/akIq10ZKeLVilRGI+v3u8wBeqGPJyjQ3zY2UE4gvha50jaDakHTET6wr4732VaYWCBntAE+wvE1eZpdtKdbUAT/ctaf/fLXBlTuOmBVPVytLspbC5THNNGOAGTMV3VN1zJuUXmTLeUjwcEWq7Q8=,iv:UAX/t5ZRFwodOUltVfBf7kqMxqVxCWgLy+PWdkNArXQ=,tag:jcVPXQL87BwI9tNjWn/0sw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
