proxmox:
    user: ENC[AES256_GCM,data:6TbDUU0k26U=,iv:qNFVwlg1MFIGVu6opVXBjlDE+cQTCza0nC+AyeU6ZXU=,tag:GCT38N7B8t1kiv1Xk1znww==,type:str]
    password: ENC[AES256_GCM,data:KMyPx2/f+htVzfU=,iv:t23QKe9VZqId/MDVpgKGmqEbAgcMwzhXO8npw05lhQo=,tag:Lr82rWdjoydaZZLZiNEQdA==,type:str]
git:
    deploy-key:
        private: ENC[AES256_GCM,data:yxCDj8RSfAEjqHdwTY0JbHASJecDF26mHheh5l3WoJ2tZxMHPWj8pdAw7gRrV/ddplC818q9X1k43+wuajEXBHo/eOM5ngIlpB/XZzO+2Frh7tZYzlackpt7rJ+8YXZ1MwVzuyvnMBQKf1H/4Y9ZqBWY55dLcCZnXYl1r9f91SYE9lkC5CTTYCi52mHOxH5b9YzBOEBnpU8Mfi2XtyxRLINfP4e5/AR57KT1fMJ7tyXq36hYcdixjcHR/VvVyQGZEGbpCXd9iQnZB7xfGcPfzq1S1/0mcLsOyYQxlMRunFEsZbBhdQPeq3dMThlWbgHFuCQdqsP+QAntQVZL9MBursji3/VmirPStKGIBj7uQFoVkPk4K1ntfW9k20HQ7DA=,iv:Ws2702RvyI9N6oqmOLWiAyMj/orb4ESOC3r/tp6GoG4=,tag:fZpHj9oUunEuNTTSAT68Og==,type:str]
        public: ENC[AES256_GCM,data:w9seEr/E0GDNYXzrMJm49p0TnKZ3dzexybrwkie4/zPgYJPHZY8UAn6hvpFlwYIAjbBalGu40s9yPXJvXjbqjuH52pmJcBD+ne/yS4QTs8kM0M8XCRgfhs0qlRRZYDAFnwRbVeUPfXn3jx7+qQDrIiCMcLBeGRGZk9DQZc0Kw2enr88Qu2h6uoSqc5WfUlt88LDYqZuf233yaVT7EzhRfD3NANKYEmmRNyDY1kej+3tlybCLbHG2Px3ye1JYCjvRqQrgmKe2Pqsydptu,iv:VyjE7aJzo5UQsnDXY0BwZzFbJBwSyiR/62XKezWMM2Q=,tag:VZomABxk8Lk4wjsS0Dk46w==,type:str]
age:
    agekey: ENC[AES256_GCM,data:JzKZT7luz9nnO/APg5Y7rk20nHKHLtWQnE1+vOARF0wno9t/lS2ows/sYMjgDUtJF2yeT8rNpFxBAN/Q+K6i02oYETeu3u3Z/QI=,iv:ukVVv4K2bHe3n2ygYOVa862n1kpaWcVuH4aawz6f8ZE=,tag:vq+xPSw43fe9JvTZtAryqQ==,type:str]
    public: ENC[AES256_GCM,data:coFSEe3LnJZyQy5tRpgCr0bEiPSejlPEfIs/S0gHPmlvgIvrmJjHPbfzZ1/L+8EWeMvrD45aK/PjA7WQpZY=,iv:F//fVS/irJBVAeGZerDdQbOY88q5VtOGKOXKdU5rwMg=,tag:4Nrp/O436m2jL9qUADlLsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lxv87gr62gf94et9cgj85ae7xuuxr3lqf0j959vewh4f3pdp050sqakepu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSm8vS3RWRlE4RllVa3d4
            UjJCMEtlRkh2UGVUZ2lOWG52YVZTZUZmZFhvCmFkL2pybXpPS1RONDk4a1dkaTNF
            UVFrTWhNbGtvRVpiMXExelRmV3dHWGMKLS0tIGczS3pxRWRkUGZHeEFPdW9YQzBp
            L29FZldyQjBSbWE1OFUrZW1WQjc0cW8KaLV6/318eNcDBjTjwMgMvHUjEFLPE3lX
            OCxhOVLdlwkzOH9AJVrbiCRjWzO0t1vz9VrrzIGMkT95bUU93Wc2yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T15:43:21Z"
    mac: ENC[AES256_GCM,data:ty9pinRKzpvsuDqGtOz3OytDTwUng4Z4nkpFQpe8uOtZkE9PjXCFnRK6KskEqn1hVGV20a2pBWQBqXnrFO34HqFB5w/dNQXlJbNHcp5A7WaxbfZB/INpkHkqmhkz1eS5oNR2MBQ5pH73VrxeW65sX/RPhjpR9aCuu/joZ8PzWtE=,iv:B5JYpQSzYe2nNY5axYkZWSZ97GTQflFBNtMzg/jpvPE=,tag:xDxhwC8TA6unn5QcJkv7sQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
