apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-certificates
  namespace: step-certificates
spec:
  chart:
    spec:
      chart: step-certificates
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
  interval: 1m0s
  values:
    fullnameOverride: step-certificates
    existingSecrets: 
      enabled: true
      ca: true
      issuer: false
      configAsSecret: false
      sshHostCa: false
      sshUserCa: false

    bootstrap:
      secrets: false
      enabled: false
      configmaps: false

    inject:
      enabled: false
    