apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: step-certificates
  namespace: step-certificates
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`ca.lab.home.molier.net`)
    services:
    - name: step-certificates
      port: 443