apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.certs.yaml
- configmap.config.yaml
- secret.ca-password.sops.yaml
- secret.secrets.sops.yaml
- helmrelease.yaml
- ingressroute.yaml